# Canonical source manifest for Spectral engine modules.
#
# Required input:
#   SPECTRAL_ENGINE_ROOT - absolute or relative path to spectral_engine/

if(NOT DEFINED SPECTRAL_ENGINE_ROOT OR "${SPECTRAL_ENGINE_ROOT}" STREQUAL "")
    message(FATAL_ERROR "SPECTRAL_ENGINE_ROOT must be set before including source-manifest.cmake")
endif()

get_filename_component(SPECTRAL_ENGINE_ROOT "${SPECTRAL_ENGINE_ROOT}" ABSOLUTE)
get_filename_component(SPECTRAL_MANIFEST_REPO_ROOT "${SPECTRAL_ENGINE_ROOT}/.." ABSOLUTE)

set(SPECTRAL_CORE_DIR "${SPECTRAL_ENGINE_ROOT}/core")
set(SPECTRAL_CMD_DIR "${SPECTRAL_ENGINE_ROOT}/cmd")
set(SPECTRAL_CMD_CLI_DIR "${SPECTRAL_ENGINE_ROOT}/cmd/cli")
set(SPECTRAL_ANALYSIS_DIR "${SPECTRAL_ENGINE_ROOT}/analysis")
set(SPECTRAL_RUNTIME_DIR "${SPECTRAL_ENGINE_ROOT}/runtime")
set(SPECTRAL_SYNTH_API_DIR "${SPECTRAL_ENGINE_ROOT}/synth/api")
set(SPECTRAL_SYNTH_BACKEND_CPU_DIR "${SPECTRAL_ENGINE_ROOT}/synth/backends/cpu")
set(SPECTRAL_SYNTH_BACKEND_ARM_DIR "${SPECTRAL_ENGINE_ROOT}/synth/backends/arm")
set(SPECTRAL_SYNTH_BACKEND_SIM_DIR "${SPECTRAL_ENGINE_ROOT}/synth/backends/sim")
set(SPECTRAL_SYNTH_BACKEND_GPU_CUDA_DIR "${SPECTRAL_ENGINE_ROOT}/synth/backends/gpu/cuda")
set(SPECTRAL_SYNTH_BACKEND_GPU_METAL_DIR "${SPECTRAL_ENGINE_ROOT}/synth/backends/gpu/metal")
set(SPECTRAL_SYNTH_MATH_DIR "${SPECTRAL_ENGINE_ROOT}/synth/math")

set(SPECTRAL_SOURCE_ENTRY_MAIN "${SPECTRAL_CMD_CLI_DIR}/main.c")
set(SPECTRAL_SOURCE_CONVERT_SEGMENTS_ENTRY "${SPECTRAL_CMD_DIR}/convert_segments.c")

set(SPECTRAL_SOURCES_CORE
    "${SPECTRAL_CORE_DIR}/spectral_segment_math.c"
    "${SPECTRAL_CORE_DIR}/oscillator.c"
    "${SPECTRAL_CORE_DIR}/oscillator_simd.c"
    "${SPECTRAL_CORE_DIR}/spectral_backend.c"
    "${SPECTRAL_CORE_DIR}/spectral_fs.c"
    "${SPECTRAL_CORE_DIR}/spectral_common.c"
    "${SPECTRAL_CORE_DIR}/spectral_envelope.c"
    "${SPECTRAL_CORE_DIR}/spectral_error.c"
    "${SPECTRAL_CORE_DIR}/spectral_fast_math.c"
    "${SPECTRAL_CORE_DIR}/spectral_hash_xx32_xx3.c"
    "${SPECTRAL_CORE_DIR}/spectral_in.c"
    "${SPECTRAL_CORE_DIR}/spectral_log.c"
    "${SPECTRAL_CORE_DIR}/spectral_lut.c"
    "${SPECTRAL_CORE_DIR}/spectral_out.c"
    "${SPECTRAL_CORE_DIR}/spectral_resource_fs.c"
    "${SPECTRAL_CORE_DIR}/spectral_seg_cache.c"
    "${SPECTRAL_CORE_DIR}/spectral_seg_cache_fs.c"
    "${SPECTRAL_CORE_DIR}/spectral_segment_mt.c"
    "${SPECTRAL_CORE_DIR}/spectral_segment_parser.c"
    "${SPECTRAL_CORE_DIR}/spectral_segment_pool.c"
    "${SPECTRAL_CORE_DIR}/spectral_synth_internal.c"
    "${SPECTRAL_CORE_DIR}/spectral_vector_ops.c"
    "${SPECTRAL_CORE_DIR}/spectral_wavetable.c"
    "${SPECTRAL_CORE_DIR}/spectral_windows.c")

set(SPECTRAL_SOURCES_RUNTIME
    "${SPECTRAL_RUNTIME_DIR}/spectral_utils.c"
    "${SPECTRAL_RUNTIME_DIR}/spectral_console.c")

set(SPECTRAL_SOURCES_MONITORING
    "${SPECTRAL_RUNTIME_DIR}/spectral_perf.c")

set(SPECTRAL_SOURCES_RUNTIME_PERF_MODEL
    "${SPECTRAL_RUNTIME_DIR}/spectral_perf_embedded.c"
    "${SPECTRAL_RUNTIME_DIR}/spectral_perf_model.c")

set(SPECTRAL_SOURCES_ANALYSIS_PROC
    "${SPECTRAL_ANALYSIS_DIR}/spectral_processing_chain.c"
    "${SPECTRAL_ANALYSIS_DIR}/spectral_proc_adaptive_track_density.c"
    "${SPECTRAL_ANALYSIS_DIR}/spectral_proc_johnston_1988.c"
    "${SPECTRAL_ANALYSIS_DIR}/spectral_proc_serra_smith_1990.c")

set(SPECTRAL_SOURCES_ANALYSIS
    "${SPECTRAL_ANALYSIS_DIR}/spectral_analysis.c"
    "${SPECTRAL_ANALYSIS_DIR}/spectral_analysis_fft.c"
    "${SPECTRAL_ANALYSIS_DIR}/spectral_analysis_full.c"
    "${SPECTRAL_ANALYSIS_DIR}/spectral_analysis_fused.c"
    "${SPECTRAL_ANALYSIS_DIR}/spectral_peak_interp.c"
    ${SPECTRAL_SOURCES_ANALYSIS_PROC}
    "${SPECTRAL_ANALYSIS_DIR}/spectral_peak_track.c")

set(SPECTRAL_SOURCES_CLI
    "${SPECTRAL_CMD_CLI_DIR}/spectral_cli.c"
    "${SPECTRAL_CMD_CLI_DIR}/spectral_cli_pipeline.c"
    ${SPECTRAL_SOURCES_RUNTIME})

set(SPECTRAL_SOURCES_SYNTH_CPU "${SPECTRAL_SYNTH_BACKEND_CPU_DIR}/spectral_synth_cpu.c")
set(SPECTRAL_SOURCES_SYNTH_EMBEDDED
    "${SPECTRAL_SYNTH_BACKEND_ARM_DIR}/spectral_synth_arm32.c"
    "${SPECTRAL_SYNTH_BACKEND_ARM_DIR}/spectral_debug_embedded_arm.c"
    "${SPECTRAL_SYNTH_MATH_DIR}/spectral_q15.c")
set(SPECTRAL_SOURCES_SYNTH_SIMULATION "${SPECTRAL_SYNTH_BACKEND_SIM_DIR}/spectral_synth_simulation.c")
set(SPECTRAL_SOURCES_SYNTH_METAL "${SPECTRAL_SYNTH_BACKEND_GPU_METAL_DIR}/spectral_synth_metal.m")
set(SPECTRAL_SOURCES_SYNTH_CUDA "${SPECTRAL_SYNTH_BACKEND_GPU_CUDA_DIR}/spectral_synth_cuda.cu")

set(SPECTRAL_SOURCES_DAISY_ENGINE
    "${SPECTRAL_SYNTH_BACKEND_ARM_DIR}/spectral_synth_arm32.c"
    "${SPECTRAL_SYNTH_BACKEND_ARM_DIR}/spectral_debug_embedded_arm.c"
    "${SPECTRAL_SYNTH_MATH_DIR}/spectral_q15.c"
    "${SPECTRAL_CORE_DIR}/spectral_wavetable.c")

set(SPECTRAL_SOURCES_HOST_CLI_STACK
    ${SPECTRAL_SOURCE_ENTRY_MAIN}
    ${SPECTRAL_SOURCES_CLI}
    ${SPECTRAL_SOURCES_CORE})

set(SPECTRAL_SOURCES_HOST_Q15_STACK
    ${SPECTRAL_SOURCES_ANALYSIS_PROC}
    ${SPECTRAL_SOURCES_RUNTIME_PERF_MODEL}
    ${SPECTRAL_SOURCES_SYNTH_EMBEDDED}
    ${SPECTRAL_SOURCES_SYNTH_SIMULATION})

set(SPECTRAL_SOURCES_HOST_MONITORED_Q15_STACK
    ${SPECTRAL_SOURCES_HOST_CLI_STACK}
    ${SPECTRAL_SOURCES_HOST_Q15_STACK}
    ${SPECTRAL_SOURCES_MONITORING})

set(SPECTRAL_SOURCES_TARGET_DESKTOP
    ${SPECTRAL_SOURCE_ENTRY_MAIN}
    ${SPECTRAL_SOURCES_CLI}
    ${SPECTRAL_SOURCES_ANALYSIS}
    ${SPECTRAL_SOURCES_SYNTH_CPU}
    ${SPECTRAL_SOURCES_CORE}
    ${SPECTRAL_SOURCES_MONITORING})

set(SPECTRAL_SOURCES_TARGET_SIMULATE
    ${SPECTRAL_SOURCES_HOST_MONITORED_Q15_STACK}
    ${SPECTRAL_SOURCES_ANALYSIS}
    ${SPECTRAL_SOURCES_SYNTH_CPU})

set(SPECTRAL_SOURCES_TARGET_SIMULATE_DAISY
    ${SPECTRAL_SOURCES_HOST_MONITORED_Q15_STACK})

set(SPECTRAL_SOURCES_TARGET_EMBEDDED_ARM
    ${SPECTRAL_SOURCES_HOST_MONITORED_Q15_STACK}
    ${SPECTRAL_SOURCES_ANALYSIS})

set(SPECTRAL_SOURCES_TARGET_EMBEDDED_ARM_RESTRICTED
    ${SPECTRAL_SOURCES_HOST_CLI_STACK}
    ${SPECTRAL_SOURCES_HOST_Q15_STACK})

set(SPECTRAL_ENGINE_INCLUDE_DIRS
    "${SPECTRAL_CORE_DIR}"
    "${SPECTRAL_CMD_DIR}"
    "${SPECTRAL_CMD_CLI_DIR}"
    "${SPECTRAL_ANALYSIS_DIR}"
    "${SPECTRAL_RUNTIME_DIR}"
    "${SPECTRAL_SYNTH_API_DIR}"
    "${SPECTRAL_SYNTH_BACKEND_ARM_DIR}"
    "${SPECTRAL_SYNTH_MATH_DIR}")

set(SPECTRAL_SIMDE_INCLUDE_DIR  "${SPECTRAL_MANIFEST_REPO_ROOT}/third_party/simde")
set(SPECTRAL_XXHASH_INCLUDE_DIR "${SPECTRAL_MANIFEST_REPO_ROOT}/third_party/xxHash")
