"""Generate pre-computed Q15 sine LUT for flash-resident storage."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np

# When executed directly (python lut_generator.py), __package__ is unset.
# Patch sys.path once so relative imports work in both modes.
if __package__ in {None, ""}:
    _tools_root = str(Path(__file__).resolve().parents[2])
    if _tools_root not in sys.path:
        sys.path.insert(0, _tools_root)
    __package__ = "spectral_tools.generators"  # noqa: A001

from ..core.console import Console
from ..core.utils import read_utf8_lf, write_utf8_lf

DEFAULT_BITS = 12
MIN_BITS = 6
MAX_BITS = 16
DEFAULT_OUTPUT_PATH = Path("spectral_engine/core/spectral_lut_data.h")
Q15_MAX = 32767
Q15_MIN = -32768
Q15_SCALE = 32700.0
VALUES_PER_LINE = 16
NEWLINE = "\n"


def generate_lut(bits: int) -> list[int]:
    """Generate Q15 sine LUT matching spectral_lut_init_sine() exactly."""
    size = 1 << bits
    phases = np.linspace(0.0, 2.0 * np.pi, num=size + 1, endpoint=True, dtype=np.float64)
    lut = np.clip((np.sin(phases) * Q15_SCALE).astype(np.int32), Q15_MIN, Q15_MAX)
    values = [int(value) for value in lut.tolist()]

    # Force exact cardinal values (matches runtime init)
    values[0] = 0
    values[size // 2] = 0
    values[size // 4] = int(Q15_SCALE)
    values[(3 * size) // 4] = int(-Q15_SCALE)
    return values


def format_c_array(lut: list[int], bits: int) -> str:
    """Format LUT as a C const array with linker section annotation."""
    size = 1 << bits
    lines = [
        "/* AUTO-GENERATED by tools/spectral_tools/generators/lut_generator.py -- do not edit */",
        f"/* Sine LUT: {size} entries + 1 wrap, Q15, scale={int(Q15_SCALE)} */",
        "#ifndef SPECTRAL_LUT_DATA_H",
        "#define SPECTRAL_LUT_DATA_H",
        "",
        '#include "spectral_lut.h"',
        '#include "spectral_config.h"',
        "",
        "#if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L",
        f"_Static_assert(SPECTRAL_OSC_LUT_BITS == {bits},",
        f'    "LUT data generated for {bits}-bit table; regenerate via spectral_tools.generators.lut_generator");',
        "#endif",
        "",
        "const q15_t spectral_lut_flash[SPECTRAL_OSC_LUT_SIZE + 1]",
        '    __attribute__((section(".rodata.osc_lut"), aligned(4))) = {',
    ]

    for offset in range(0, len(lut), VALUES_PER_LINE):
        chunk = lut[offset : offset + VALUES_PER_LINE]
        values = ", ".join(f"{value:6d}" for value in chunk)
        comma = "," if offset + VALUES_PER_LINE < len(lut) else ""
        lines.append(f"    {values}{comma}")

    lines.extend(
        [
            "};",
            "",
            "#endif /* SPECTRAL_LUT_DATA_H */",
            "",
        ]
    )
    return NEWLINE.join(lines)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate or verify the Q15 sine LUT for flash storage")
    parser.add_argument(
        "--mode",
        choices=("generate", "verify"),
        default="generate",
        help="generate: (re)write the committed header. verify: fail if the committed "
        "header is not byte-identical to what this generator produces (drift guard).",
    )
    parser.add_argument(
        "--bits",
        type=int,
        default=DEFAULT_BITS,
        help=f"LUT size in bits (default: {DEFAULT_BITS} = {1 << DEFAULT_BITS} entries)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT_PATH,
        help="Output header file path",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    console = Console()

    if args.bits < MIN_BITS or args.bits > MAX_BITS:
        console.print_error(f"bits must be {MIN_BITS}-{MAX_BITS}, got {args.bits}")
        return 1

    output_path = args.output.resolve()
    content = format_c_array(generate_lut(args.bits), args.bits)

    if args.mode == "verify":
        if not output_path.exists():
            console.print_error(f"{output_path} is missing; run --mode generate")
            return 1
        if read_utf8_lf(output_path) != content:
            console.print_error(
                f"{output_path} has DRIFTED from lut_generator.py "
                f"({args.bits}-bit) -- regenerate via --mode generate"
            )
            return 1
        print(f"Verified {output_path}: matches the {args.bits}-bit generator")
        return 0

    output_path.parent.mkdir(parents=True, exist_ok=True)
    write_utf8_lf(output_path, content)
    size = 1 << args.bits
    mem_bytes = (size + 1) * 2  # q15_t = 2 bytes
    print(f"Generated {output_path}: {size + 1} entries, {mem_bytes} bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
