"""Generated-artifact registry gate (kernel-hardening I).

Every committed generated source must (a) be a known, registered artifact and
(b) have a working verify-on-build drift guard. The hole this closes:
spectral_lut_data.h shipped for a long time as a committed generated header with
NO verify target — it could silently drift from its generator. These tests make
that class of hole fail loudly:

  - registry-completeness: the set of committed engine sources bearing the
    `AUTO-GENERATED by tools/spectral_tools/generators/<x>.py` banner must equal
    the registered set below (keep in sync with
    docs/core_audit/reference/GENERATED_ARTIFACTS.md). A new generated file that
    isn't registered + verify-wired fails here.
  - per-artifact verify: each generator's `--mode verify` passes against the
    committed file (fail-on-bug: corrupt the committed file -> verify returns 1).
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
ENGINE = ROOT / "spectral_engine"
BANNER = re.compile(r"AUTO-GENERATED by tools/spectral_tools/generators/(\S+\.py)")

# The registry: committed generated source -> (generator module, verify argv).
# Single source of truth for humans is GENERATED_ARTIFACTS.md; this is the gate.
REGISTRY = {
    "core/spectral_hash_resources_xx32_xx3.c": (
        "resource_hashes.py",
        ["spectral_tools.generators.resource_hashes", "--mode", "verify"],
    ),
    "core/spectral_lut_data.h": (
        "lut_generator.py",
        ["spectral_tools.generators.lut_generator", "--mode", "verify"],
    ),
    "drivers/metal/spectral_osc_metal_generated.h": (
        "metal_osc.py",
        None,  # metal verify needs --formulas/... paths; covered by the cmake verify_metal_osc
    ),
}


def _committed_generated_sources() -> set[str]:
    """All git-tracked engine .c/.h files carrying the generator banner."""
    out = subprocess.run(
        ["git", "grep", "-l", "AUTO-GENERATED by tools/spectral_tools/generators/",
         "--", "spectral_engine/*.c", "spectral_engine/*.h"],
        cwd=ROOT, capture_output=True, text=True,
    )
    found = set()
    for line in out.stdout.splitlines():
        line = line.strip()
        if not line:
            continue
        found.add(str(Path(line).relative_to("spectral_engine")))
    return found


def test_registry_is_complete():
    """Every banner-bearing committed engine source is registered (and therefore
    verify-wired). A new generated file that skips the registry fails here."""
    found = _committed_generated_sources()
    registered = set(REGISTRY)
    unregistered = found - registered
    assert not unregistered, (
        f"committed generated file(s) not in the registry (no verify guard?): "
        f"{sorted(unregistered)}. Add a verify target + a GENERATED_ARTIFACTS.md row "
        f"+ a REGISTRY entry here."
    )
    missing = registered - found
    assert not missing, (
        f"registered artifact(s) no longer present/banner-tagged: {sorted(missing)}. "
        f"Update the registry."
    )


@pytest.mark.parametrize("rel,spec", [(k, v) for k, v in REGISTRY.items() if v[1] is not None])
def test_artifact_verify_passes(rel, spec):
    """The committed artifact matches its generator (verify mode exits 0)."""
    _module, argv = spec
    r = subprocess.run(
        [sys.executable, "-m", *argv],
        cwd=ROOT, env={"PYTHONPATH": str(ROOT / "tools"), "PATH": __import__("os").environ["PATH"]},
        capture_output=True, text=True,
    )
    assert r.returncode == 0, (
        f"{rel} failed verify (drifted from its generator?):\n{r.stdout}\n{r.stderr}"
    )


if __name__ == "__main__":
    sys.exit(pytest.main([__file__, "-v"]))
