"""Workload fixture SSOT for the M7 measurement stack.

One fixture definition, two consumers: the QEMU runner compiles the generated
C header (qemu_main.c includes it), and Python reports carry the same spec so
every counts table is traceable to its exact workload. Generation is
deterministic — same spec, byte-identical header (generators discipline,
ADR-0001 rules 3/5).

The default fixture is the standard counts workload (M7_PERF_MODEL_PLAN.md):
9 staggered 8192-sample voices (odd count keeps one voice unpaired past
dual-MAC pairing), rendered in 48-sample blocks (DAISY_AUDIO_BLOCK_SIZE — the
REAL codec callback, not the 256-sample engine buffer cap; measuring at 256
under-priced per-block overhead by ~13%), total a multiple of 48 that contains
all voices, fades exercised at every boundary.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass, field
from typing import Any

HEADER_NAME = "spectral_fixture_generated.h"


@dataclass(frozen=True, slots=True)
class Voice:
    start: int          # output-sample index; fixture must be monotonic by start
    length: int         # samples (uint16 in SpectralSegmentQ15)
    freq_hz: float
    amp: float          # linear [0, 1); converted with FLOAT_TO_Q15 in C
    phase_q15: int = 0

    def validate(self) -> None:
        if not 0 < self.length <= 0xFFFF:
            raise ValueError(f"voice length {self.length} outside uint16")
        if not 0.0 <= self.amp < 1.0:
            raise ValueError(f"voice amp {self.amp} outside [0, 1)")
        if self.freq_hz <= 0.0:
            raise ValueError(f"voice freq {self.freq_hz} must be positive")


@dataclass(frozen=True, slots=True)
class WorkloadFixture:
    name: str
    sample_rate: int
    total_samples: int
    block_samples: int
    voices: tuple[Voice, ...] = field(default_factory=tuple)

    def validate(self) -> None:
        if self.block_samples <= 0 or self.total_samples % self.block_samples:
            raise ValueError("total_samples must be a positive multiple of block_samples")
        if not self.voices:
            raise ValueError("fixture needs at least one voice")
        last_start = -1
        for voice in self.voices:
            voice.validate()
            if voice.start < last_start:
                raise ValueError("voices must be monotonic by start (loader validates this)")
            last_start = voice.start

    def spec_dict(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "sample_rate": self.sample_rate,
            "total_samples": self.total_samples,
            "block_samples": self.block_samples,
            "voices": [
                {
                    "start": v.start,
                    "length": v.length,
                    "freq_hz": v.freq_hz,
                    "amp": v.amp,
                    "phase_q15": v.phase_q15,
                }
                for v in self.voices
            ],
        }

    def digest(self) -> str:
        """Stable content hash; reports carry it so counts↔workload pairing is checkable."""
        canon = repr(sorted(self.spec_dict().items())).encode("utf-8")
        return hashlib.sha256(canon).hexdigest()[:16]

    def to_c_header(self) -> str:
        self.validate()
        lines = [
            f"/* AUTO-GENERATED by spectral_tools.performance.embedded.fixture -- do not edit",
            f" * fixture: {self.name}  digest: {self.digest()} */",
            "#ifndef SPECTRAL_FIXTURE_GENERATED_H",
            "#define SPECTRAL_FIXTURE_GENERATED_H",
            "",
            f"#define FIXTURE_N_SEG   {len(self.voices)}u",
            f"#define FIXTURE_BLOCK   {self.block_samples}u",
            f"#define FIXTURE_TOTAL   {self.total_samples}u",
            f"#define FIXTURE_SR      {self.sample_rate}u",
            "",
            "/* start, length, freq_hz, amp, phase_q15 */",
            "#define FIXTURE_VOICES(X) \\",
        ]
        rows = [
            f"    X({v.start}u, {v.length}u, {v.freq_hz!r}f, {v.amp!r}f, {v.phase_q15})"
            for v in self.voices
        ]
        lines.append(" \\\n".join(rows))
        lines += ["", "#endif /* SPECTRAL_FIXTURE_GENERATED_H */", ""]
        return "\n".join(lines)


def default_fixture() -> WorkloadFixture:
    return WorkloadFixture(
        name="stagger9-8k-b48",
        sample_rate=48_000,
        # Render at the real 48-sample Daisy codec block (DAISY_AUDIO_BLOCK_SIZE). total is the
        # smallest multiple of 48 that still contains the last voice (ends at 8192+8192=16384):
        # 48*342 = 16416. The 256-block fixture under-priced per-block overhead (seed/fade/prologue)
        # by ~13% (process_insns 2.10M@256 -> 2.37M@48) — the device never runs the 256 path.
        total_samples=16_416,
        block_samples=48,
        voices=tuple(
            Voice(start=i * 1024, length=8192, freq_hz=220.0 * (i + 1), amp=0.05)
            for i in range(9)
        ),
    )
