/* AUTO-GENERATED by tools/gen_resource_hashes.py — do not edit */
/* Hash algorithms: host=xxh3_64, embedded=xxh32 */
/*
 * Note:
 *   Preprocessor-time file hashing is not supported by C/C11.
 *   Build-time equivalence is enforced by CMake verify_resource_hashes target.
 *
 * Example (commented) static assert style:
 *   // _Static_assert(1, "resource hash equivalence verified in build step");
 */
#include <stddef.h>
#include <stdint.h>
#include "spectral_resource_fs.h"

const SpectralResourceFsEntry spectral_resource_hashes[] = {
#if SPECTRAL_EMBEDDED || SPECTRAL_IS_EMBEDDED_SIM
#else
#endif
};

const size_t spectral_resource_hashes_count = (size_t)0u;
