/* AUTO-GENERATED by tools/spectral_tools/generators/resource_hashes.py — do not edit */
/* Hash algorithms: host=xxh3_64, embedded=xxh32 */
/*
 * Note:
 *   Preprocessor-time file hashing is not supported by C/C11.
 *   Build-time equivalence is enforced by CMake verify_resource_hashes target.
 *
 * Example (commented) static assert style:
 *   // _Static_assert(1, "resource hash equivalence verified in build step");
 */
#include <stddef.h>
#include <stdint.h>
#include "spectral_resource_fs.h"

const SpectralResourceFsEntry spectral_resource_hashes[] = {
#if SPECTRAL_EMBEDDED || SPECTRAL_IS_EMBEDDED_SIM
    { UINT32_C(0x21ceaaae), UINT64_C(0x00000000f591d7d7), (size_t)27530578u },
    { UINT32_C(0x4489d2ed), UINT64_C(0x000000009dcc81d2), (size_t)6901838u },
    { UINT32_C(0x112bbc43), UINT64_C(0x000000009a9c4bc1), (size_t)176444u },
#else
    {"testing/motormouth_test1_uncompressed_spear.txt", UINT64_C(0x9ee48db333f894d6), (size_t)27530578u},
    {"testing/shakespeare_he_saw_the_cat.wav", UINT64_C(0x89a01685e30b16b8), (size_t)6901838u},
    {"testing/sin_440hz.wav", UINT64_C(0x0f1432c85ea0bd35), (size_t)176444u},
#endif
};

const size_t spectral_resource_hashes_count = (size_t)3u;
