#!/usr/bin/env python3
"""Generate pre-computed Q15 sine LUT for flash-resident storage.

Outputs a C header file (spectral_lut_data.h) containing a const array
that can be placed in flash via linker section annotation. This saves
~8KB of SRAM on embedded targets.

Usage:
    python3 tools/gen_lut.py [--bits N] [--output PATH]

Defaults:
    --bits 12     (4096 entries + 1 wrap point = 4097 entries)
    --output spectral_engine/core/spectral_lut_data.h
"""

import argparse
import math
import sys


def generate_lut(bits: int) -> list[int]:
    """Generate Q15 sine LUT matching spectral_lut_init_sine() exactly."""
    size = 1 << bits
    scale = 32700.0  # Q15_MAX minus headroom for interpolation

    lut = []
    for i in range(size + 1):
        phase = i / size * 2.0 * math.pi
        val = int(math.sin(phase) * scale)
        # Clamp to Q15 range
        val = max(-32768, min(32767, val))
        lut.append(val)

    # Force exact cardinal values (matches runtime init)
    lut[0] = 0
    lut[size // 2] = 0
    lut[size // 4] = int(scale)
    lut[3 * size // 4] = int(-scale)

    return lut


def format_c_array(lut: list[int], bits: int) -> str:
    """Format LUT as a C const array with linker section annotation."""
    size = 1 << bits
    lines = []
    lines.append("/* AUTO-GENERATED by tools/gen_lut.py — do not edit */")
    lines.append(f"/* Sine LUT: {size} entries + 1 wrap, Q15, scale=32700 */")
    lines.append("#ifndef SPECTRAL_LUT_DATA_H")
    lines.append("#define SPECTRAL_LUT_DATA_H")
    lines.append("")
    lines.append('#include "spectral_lut.h"')
    lines.append('#include "spectral_config.h"')
    lines.append("")
    lines.append("#if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L")
    lines.append(f"_Static_assert(SPECTRAL_OSC_LUT_BITS == {bits},")
    lines.append(f'    "LUT data generated for {bits}-bit table, rebuild with gen_lut.py");')
    lines.append("#endif")
    lines.append("")
    lines.append("const q15_t spectral_lut_flash[SPECTRAL_OSC_LUT_SIZE + 1]")
    lines.append('    __attribute__((section(".rodata.osc_lut"), aligned(4))) = {')

    # Format 16 values per line
    for i in range(0, len(lut), 16):
        chunk = lut[i:i + 16]
        vals = ", ".join(f"{v:6d}" for v in chunk)
        comma = "," if i + 16 < len(lut) else ""
        lines.append(f"    {vals}{comma}")

    lines.append("};")
    lines.append("")
    lines.append("#endif /* SPECTRAL_LUT_DATA_H */")
    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate Q15 sine LUT for flash storage")
    parser.add_argument("--bits", type=int, default=12,
                        help="LUT size in bits (default: 12 = 4096 entries)")
    parser.add_argument("--output", type=str,
                        default="spectral_engine/core/spectral_lut_data.h",
                        help="Output header file path")
    args = parser.parse_args()

    if args.bits < 6 or args.bits > 16:
        print(f"Error: bits must be 6-16, got {args.bits}", file=sys.stderr)
        sys.exit(1)

    lut = generate_lut(args.bits)
    content = format_c_array(lut, args.bits)

    with open(args.output, "w") as f:
        f.write(content)

    size = 1 << args.bits
    mem_bytes = (size + 1) * 2  # Q15 = 2 bytes each
    print(f"Generated {args.output}: {size + 1} entries, {mem_bytes} bytes")


if __name__ == "__main__":
    main()
