/* AUTO-GENERATED by tools/spectral_tools/generators/metal_osc.py — DO NOT EDIT.
 *
 * Single source of truth for the Metal MSL oscillator + segment math:
 *   core/spectral_osc_formulas.h   (waveforms, phase, fade)
 *   core/spectral_segment_math.h   (segment alpha/beta/d_amp/phase/amp)
 *   core/oscillator.h              (SPECTRAL_OSC_TIMBRE_LIST ordering)
 *
 * Regenerate: cmake --build build --target generate_metal_osc
 * Verify:     cmake --build build --target verify_metal_osc
 *
 * osc_formulas_version=6 segment_math_version=1
 */
#ifndef SPECTRAL_OSC_METAL_GENERATED_H
#define SPECTRAL_OSC_METAL_GENERATED_H

#if defined(__APPLE__) && !defined(__CUDACC__)

const char* oscillator_metal_source =
"#define TIMBRE_SINE    0\n"
"#define TIMBRE_SAW     1\n"
"#define TIMBRE_SQUARE  2\n"
"#define TIMBRE_TRIANGLE 3\n"
"#define TIMBRE_ASIN    4\n"
"#define TIMBRE_PARABOLA 5\n"
"\n"
"#define TWO_PI " SPECTRAL_STR(SPECTRAL_TWO_PI) "\n"
"#define INV_TWO_PI " SPECTRAL_STR(SPECTRAL_INV_TWO_PI) "\n"
"#define INV_PI " SPECTRAL_STR(SPECTRAL_INV_PI) "\n"
"#define INV_PI_SQ " SPECTRAL_STR(SPECTRAL_INV_PI_SQ) "\n"
"#define PI " SPECTRAL_STR(SPECTRAL_PI) "\n"
"\n"
"/* Must match spectral_fast_sin_inline() in spectral_osc_formulas.h.\n"
" * GPU policy: native sin, NOT the CPU deg-9 minimax poly. */\n"
"inline float oscillator_fast_sin(float x) {\n"
"    return sin(x);\n"
"}\n"
"\n"
"/* Must match spectral_normalize_phase() in spectral_osc_formulas.h.\n"
" * Inlined (no `norm` local) to preserve FMA contraction parity. */\n"
"inline float oscillator_normalize_phase(float p) {\n"
"    return p - TWO_PI * floor((p * INV_TWO_PI) + 0.5f);\n"
"}\n"
"\n"
"#define FADE_SAMPLES " SPECTRAL_STR(SPECTRAL_FADE_SAMPLES_DESKTOP) "\n"
"\n"
"/* Must match spectral_fade_envelope_gpu() in spectral_osc_formulas.h */\n"
"inline float fade_envelope(float j, float seg_len) {\n"
"    float fade_len = min(seg_len * 0.25f, (float)FADE_SAMPLES);\n"
"    if (fade_len < 1.0f) fade_len = 1.0f;\n"
"    float inv_fade = 1.0f / fade_len;\n"
"    if (j < fade_len) {\n"
"        return 0.5f * (1.0f + oscillator_fast_sin((j * inv_fade - 0.5f) * PI));\n"
"    }\n"
"    float from_end = seg_len - 1.0f - j;\n"
"    if (from_end < fade_len) {\n"
"        return 0.5f * (1.0f + oscillator_fast_sin((from_end * inv_fade - 0.5f) * PI));\n"
"    }\n"
"    return 1.0f;\n"
"}\n"
"\n"
"/* Must match spectral_osc_* waveforms in spectral_osc_formulas.h */\n"
"inline float oscillator(float phase, uint timbre) {\n"
"    float rads = oscillator_normalize_phase(phase);\n"
"    switch (timbre) {\n"
"        case TIMBRE_SINE:      return oscillator_fast_sin(rads);\n"
"        case TIMBRE_SAW:       return rads * -INV_PI;\n"
"        case TIMBRE_SQUARE:    return (rads > 0.0f) ? 1.0f : -1.0f;\n"
"        case TIMBRE_TRIANGLE:  return (1.0f - abs(rads) * INV_PI) * 2.0f - 1.0f;\n"
"        case TIMBRE_ASIN:      return asin(clamp(rads * INV_PI, -1.0f, 1.0f));\n"
"        case TIMBRE_PARABOLA:  return 1.0f - rads * rads * INV_PI_SQ;\n"
"        default:                return oscillator_fast_sin(rads);\n"
"    }\n"
"}\n";

const char* spectral_segment_math_metal_source =
"/* Generated from spectral_segment_math.h — keep the Metal tile\n"
" * kernel on the QUADRATIC phase helper (cubic is CPU-only). */\n"
"inline float segment_alpha(float omega, float pitch_factor, float inv_stretch) {\n"
"    return omega * pitch_factor * inv_stretch;\n"
"}\n"
"inline float segment_beta(float df, float pitch_factor, float inv_stretch_sq) {\n"
"    return df * pitch_factor * inv_stretch_sq;\n"
"}\n"
"inline float segment_d_amp(float da, float inv_stretch) {\n"
"    return da * inv_stretch;\n"
"}\n"
"inline float segment_phase_at(float phase0, float alpha, float beta, float sample_offset) {\n"
"    return phase0 + sample_offset * (alpha + beta * sample_offset);\n"
"}\n"
"inline float segment_amp_at(float amp0, float d_amp, float sample_offset) {\n"
"    return amp0 + d_amp * sample_offset;\n"
"}\n";

#endif /* __APPLE__ && !__CUDACC__ */

#endif /* SPECTRAL_OSC_METAL_GENERATED_H */
