# Daisy Seed ARM GCC toolchain definition.

set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

if(NOT DEFINED SPECTRAL_DAISY_TOOLCHAIN_PREFIX OR "${SPECTRAL_DAISY_TOOLCHAIN_PREFIX}" STREQUAL "")
    set(SPECTRAL_DAISY_TOOLCHAIN_PREFIX "arm-none-eabi-")
endif()

set(CMAKE_C_COMPILER "${SPECTRAL_DAISY_TOOLCHAIN_PREFIX}gcc")
set(CMAKE_CXX_COMPILER "${SPECTRAL_DAISY_TOOLCHAIN_PREFIX}g++")
set(CMAKE_ASM_COMPILER "${SPECTRAL_DAISY_TOOLCHAIN_PREFIX}gcc")
set(CMAKE_ASM_FLAGS_INIT "-x assembler-with-cpp")

set(CMAKE_AR "${SPECTRAL_DAISY_TOOLCHAIN_PREFIX}ar" CACHE FILEPATH "Archiver")
set(CMAKE_RANLIB "${SPECTRAL_DAISY_TOOLCHAIN_PREFIX}ranlib" CACHE FILEPATH "Ranlib")
set(CMAKE_OBJCOPY "${SPECTRAL_DAISY_TOOLCHAIN_PREFIX}objcopy" CACHE FILEPATH "Objcopy")
set(CMAKE_SIZE "${SPECTRAL_DAISY_TOOLCHAIN_PREFIX}size" CACHE FILEPATH "Size tool")
set(CMAKE_OBJDUMP "${SPECTRAL_DAISY_TOOLCHAIN_PREFIX}objdump" CACHE FILEPATH "Objdump")
set(CMAKE_GDB "${SPECTRAL_DAISY_TOOLCHAIN_PREFIX}gdb" CACHE FILEPATH "GDB")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
