# Q15 sine-LUT codegen — the committed flash LUT (core/spectral_lut_data.h) is the
# single source of truth, generated by tools/spectral_tools/generators/lut_generator.py.
# Before this, the LUT was the one committed generated file with NO verify-on-build guard
# (only a _Static_assert on table SIZE, not the 4097 VALUES) — it could silently drift.
# This brings it under the same generate-stamp + verify-on-build pattern as the resource
# hash table and the Metal MSL header. python_env.cmake is already included by utilities.cmake.

set(SPECTRAL_LUT_SCRIPT "${SPECTRAL_REPO_ROOT}/tools/spectral_tools/generators/lut_generator.py")
set(SPECTRAL_LUT_OUTPUT "${SPECTRAL_CORE_DIR}/spectral_lut_data.h")
# OUTPUT is a build-tree stamp, NOT the committed header: a custom-command OUTPUT is added
# to the `clean` list, so making the committed file the OUTPUT would let `--target clean`
# delete a git-tracked source. The generator still rewrites the committed header in place.
set(SPECTRAL_LUT_STAMP "${CMAKE_CURRENT_BINARY_DIR}/generate_lut.stamp")
set(SPECTRAL_LUT_RUNNER "${CMAKE_CURRENT_BINARY_DIR}/run_lut.cmake")
configure_file(
    "${SPECTRAL_ENGINE_ROOT}/cmake/scripts/run_lut.cmake.in"
    "${SPECTRAL_LUT_RUNNER}"
    @ONLY)

add_custom_command(
    OUTPUT "${SPECTRAL_LUT_STAMP}"
    COMMAND ${CMAKE_COMMAND}
            -DSPECTRAL_LUT_MODE=generate
            -P "${SPECTRAL_LUT_RUNNER}"
    COMMAND ${CMAKE_COMMAND} -E touch "${SPECTRAL_LUT_STAMP}"
    DEPENDS
        "${SPECTRAL_PYTHON_ENV_STAMP}"
        "${SPECTRAL_LUT_SCRIPT}"
        "${SPECTRAL_LUT_RUNNER}"
    COMMENT "Generating committed Q15 sine LUT (${SPECTRAL_LUT_OUTPUT})"
    VERBATIM)

add_custom_target(generate_lut
    DEPENDS "${SPECTRAL_LUT_STAMP}")
add_dependencies(generate_lut prepare_python_tools)

set_source_files_properties(
    "${SPECTRAL_LUT_OUTPUT}"
    PROPERTIES GENERATED TRUE)

add_custom_target(verify_lut
    COMMAND ${CMAKE_COMMAND}
            -DSPECTRAL_LUT_MODE=verify
            -P "${SPECTRAL_LUT_RUNNER}"
    DEPENDS
        prepare_python_tools
        generate_lut
        "${SPECTRAL_LUT_SCRIPT}"
        "${SPECTRAL_LUT_RUNNER}"
    VERBATIM)

# Gate every target that compiles spectral_lut.c on the drift check.
foreach(_lut_target IN ITEMS
        desktop simulate simulate_daisy embedded_arm embedded_arm_float embedded_arm_restricted)
    if(TARGET ${_lut_target})
        add_dependencies(${_lut_target} verify_lut)
    endif()
endforeach()
